# Site settings
title: Binary Root | A blog about Life and everything
url: https://gkiranp.github.io
author: Kiran
email: mail2kirangp@gmail.com
url: "https://gkiranp.github.io"

# Build settings
encoding: UTF-8
excerpt_separator: <!--more-->
baseurl: /
markdown: kramdown
source: .
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
