# Site settings
timezone: Asia/Kolkata
title: Binary Root | A blog about Life and everything
url: https://gkiranp.github.io
author: Kiran
email: mail2kirangp@gmail.com
url: "https://gkiranp.github.io"

# Front matter settings
jekyll_compose:
  post_default_front_matter:
    last_modified_at: 
    permalink: /:title
    description:
    image:
    published: true
    sitemap: true
    excerpt_separator: <!--more-->
    categories:
    tags:

# Build settings
encoding: UTF-8
excerpt_separator: <!--more-->
baseurl: /
markdown: kramdown
source: .
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
